/**
 * Netlify / local build step for the static IZI site.
 * Reads NEXT_PUBLIC_PAYSTACK_KEY from the environment (and optional root .env)
 * and writes js/env.js so the browser can access it at runtime.
 *
 * Netlify: set NEXT_PUBLIC_PAYSTACK_KEY in Site settings → Environment variables,
 * then this script runs as the build command and injects the value into js/env.js.
 */
const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const envFile = path.join(root, ".env");
const outFile = path.join(root, "js", "env.js");

// Load simple KEY=VALUE pairs from .env for local builds (no dotenv dependency)
function loadDotEnv(filePath) {
  if (!fs.existsSync(filePath)) return;
  const text = fs.readFileSync(filePath, "utf8");
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let val = trimmed.slice(eq + 1).trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    if (process.env[key] === undefined) {
      process.env[key] = val;
    }
  }
}

loadDotEnv(envFile);

const key = process.env.NEXT_PUBLIC_PAYSTACK_KEY || "";

const contents = `/* Generated by scripts/generate-env.js - do not edit by hand */
window.__ENV = window.__ENV || {};
window.__ENV.NEXT_PUBLIC_PAYSTACK_KEY = ${JSON.stringify(key)};
`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, contents, "utf8");

console.log(
  "[generate-env] wrote js/env.js — NEXT_PUBLIC_PAYSTACK_KEY set:",
  Boolean(key)
);
